title: Digitrecognizer
description: Digit Recognizer challenge @ https://www.kaggle.com/c/digit-recognizer
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
